# Generated by Django 5.0.6 on 2024-06-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID заявки')),
                ('student_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID студента')),
                ('room_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID кімнати')),
                ('status', models.CharField(choices=[('Submitted', 'Подано'), ('Approved', 'Одобрено'), ('Rejected', 'Відхилино')], default='Submitted', max_length=10, verbose_name='Статус')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
            },
        ),
    ]
