# Generated by Django 5.0.6 on 2024-06-21 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0002_remove_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата подачі заявки'),
            preserve_default=False,
        ),
    ]
