# Generated by Django 5.0.6 on 2024-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0003_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='desired_roommates',
            field=models.TextField(blank=True, null=True, verbose_name='Бажані сусіди'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі заявки'),
        ),
    ]
