# Generated by Django 5.0.6 on 2024-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0004_application_desired_roommates_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='application',
            table='api-applications',
        ),
    ]
