# Generated by Django 5.0.6 on 2024-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_check', '0005_alter_application_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='desired_roommates',
        ),
        migrations.AddField(
            model_name='application',
            name='desired_roommate1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_roommate2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
    ]
