# Generated by Django 5.0.6 on 2024-07-03 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_contact_number'),
        ('status_check', '0006_remove_application_desired_roommates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='desired_roommate1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='desired_roommate2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_id',
        ),
        migrations.AddField(
            model_name='application',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_from_room', to='api.room'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='applications_by_student', to='api.student'),
            preserve_default=False,
        ),
    ]
