# Generated by Django 5.0.6 on 2024-06-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(unique=True)),
                ('available_places', models.BigIntegerField()),
                ('images', models.BinaryField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')])),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('desired_roommates', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('password', models.TextField()),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.application')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_status', models.TextField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.student'),
        ),
    ]
