# Generated by Django 5.0.6 on 2024-06-18 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_desired_roommates_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
