# Generated by Django 5.0.6 on 2024-06-18 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_desired_roommates_student_desired_roommate1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='desired_roommates',
            new_name='desired_roommate1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='desired_roommate1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='desired_roommate2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='published_date',
        ),
        migrations.AddField(
            model_name='application',
            name='desired_roommate2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
