# Generated by Django 5.0.6 on 2024-06-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_desired_roommates_application_desired_roommate1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='published_date',
        ),
    ]
