# Generated by Django 5.0.6 on 2024-06-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_application_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='desired_roommate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desired_roommate', to='api.student'),
        ),
    ]
