# Generated by Django 5.0.6 on 2024-06-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking_desired_roommate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.BigIntegerField(default=1),
        ),
    ]
