# Generated by Django 5.0.6 on 2024-06-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_room_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='desired_roommate',
            new_name='desired_roommates',
        ),
    ]
