# Generated by Django 5.0.6 on 2024-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_desired_roommate_booking_desired_roommates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
