# Generated by Django 5.0.6 on 2024-07-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_rename_desired_roommate_booking_desired_roommates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
