# Generated by Django 5.0.6 on 2024-07-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_contact_number'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='student_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_bookings', to='api.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_bookings', to='api.student'),
            preserve_default=False,
        ),
    ]
