import { Inter } from "next/font/google";
import TopBar from "component/TopBar/TopBar";
import "./globals.css";
import SignIn from "../../component/SignIn/SignIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
      {children}
      </body>
    </html>
  );
}
