'use client'

import {Inter} from "next/font/google";
import TopBar from "component/TopBar/TopBar";
import "./globals.css";
import SignIn from "../../component/SignIn/SignIn";
import * as React from "react";
import {useState} from "react";
import { BookingProvider } from '../../component/context/BookingContext';

const inter = Inter({subsets: ["latin"]});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}) {
    const [popUpState, setPopUpState] = useState(false);
    return (
        <html lang="en">
        <body className={inter.className}>
        <BookingProvider>
        <TopBar showPopUp={setPopUpState} visibility={popUpState}/>
        {children}
        </BookingProvider>
        </body>
        </html>
    );
}
